package heuristics;

public enum HeuristicType {
	INFORMATIONGAIN, COVERAGE, LAPLACE, LEVERAGE, PHI_COEFFICIENT, SUPPORT, CONFIDENCE, 
	SATISFACTION, CONFIRMATION, FMEASURE, KAPPA, ODDS_RATIO, YULESQ, LIFT, COLLECTIVE_STRENGTH, 
	JACCARD, ORIGINALINFORMATIONGAIN, INFORMATIONGAINMODIFIED, WEIGHTEDINFORMATIONGAIN, TERMINI,
	POPOLO, FIORI, COLONNA, TREVI, DUCAL, COMPLEXTREVI, COMPLEXDUCAL, CALCATA
}
